### ISSUE TITLE
Onboard Intel HDA not recognized properly (ALC892)

### ISSUE THREAD

**Issue by midi1996** [ich777/unraid-sound-driver#3]
I installed this plugin on unraid 6.12-rc5, driver loads and detects my nvidia hdmi audio but not the integrated intel one. Logs from alsa-info.sh:

[alsa-info-1.txt](https://github.com/ich777/unraid-sound-driver/files/11433384/alsa-info-1.txt)

**Comment by ich777** [comment]
Sorry, I somehow missed that issue completely...

I can't do anything about that since this will require a complete rebuild from Unraid because some built in modules are missing and most of the drivers need to be recompiled including I have to provide a custom Kernel that I would have to provide through the plugin which I won't/can't do.

This plugins is mostly meant for the usage with USB Sound devices, if your built in hardware won't work I can't do anything about it.
