### ISSUE TITLE
How to use this plug-in?

### ISSUE THREAD

**Issue by dwong33** [ich777/unraid-sound-driver#4]
Hi, I see that this plug in has been updated from time to time, but the [sound-driver.plg](https://github.com/ich777/unraid-sound-driver/blob/master/sound-driver.plg) remained the same.

May I know how to use this plug-in? I want to try to install it on my unraid, and use it for my docker instances. Thank you.

**Comment by ich777** [comment]
This plugin is not active supported because it mainly supports USB Sound devices.

Just install it, if you see your sound devices you are in luck if not try using a USB Sound device <- I can't do much about the fact that most built in sound cards (AMD/Intel) systems won't work since I would have to rebuild the whole Kernel and provide it through the plugin which I won't/can't do.

**Comment by ich777** [comment]
@dwong33 do you still need help or is your question answered?

**Comment by ich777** [comment]
Closing this issue due to no response. If you still having trouble running the plugin then please feel free to open up a new issue or reopen this issue.

**Comment by dwong33** [comment]
(I replied the email but not appearing here, strange)

Thank you so much for your follow up! I am using a Asus VC 65, which has a built in sound card. So in this case, it is not likely to make it works?

Thank you.

**Comment by ich777** [comment]
> Thank you so much for your follow up! I am using a Asus VC 65, which has a built in sound card. So in this case, it is not likely to make it works?

Sadly enough no. I would recommend that you buy some cheap USB adapter, these will usually work with the plugin.

**Comment by dwong33** [comment]
Sure, let me get one from aliexpress, and try that! If I have further configuration problem. I will submit a ticket here again. Thank you!
