### ISSUE TITLE
Plg installs old version

### ISSUE THREAD

**Issue by guniv** [ich777/unraid-sound-driver#6]
Hi! I was trying today to figure out how to pass a USB webcam through UNRAID to the go2rtc docker container and figured out I somehow needed video2linux and ALSA installed on UNRAID itself. Your DVB driver worked for video2linux and this worked for ALSA.

When I used the plg to install, however, I noticed it installed 2022.07.21 rather than the latest version 2024.09.23. I should note I am on UNRAID 7.0.0-beta.3. 

I also think it would be great if you added this to community applications. Thanks so much for putting both of these together!

**Comment by ich777** [comment]
> When I used the plg to install, however, I noticed it installed 2022.07.21 rather than the latest version 2024.09.23.

I don't understand, you mean the sound driver plugin?
The latest version from the sound driver plugin is version 2022.07.21, there is no newer version available.
From where do you get 2024.09.23?



> I also think it would be great if you added this to community applications. Thanks so much for putting both of these together!

Sorry but I won't add this plugin to the CA App since I don't have time to improve it further nor to give support because this plugin is only meant for USB devices and most people will most likely ask why it won't work for their onboard sound cards, which I explained [here](https://github.com/ich777/unraid-sound-driver/issues/3#issuecomment-2193875600).

**Comment by ich777** [comment]
> I saw [this release](https://github.com/ich777/unraid-sound-driver/releases/tag/6.6.52-Unraid) and was assuming it was the newest one.

The plugin version is not bound to the package version.
The plugin installs the appropriate package for your running Unraid version on boot or installation from the plugin.

If you do:
`ls -1 /var/log/packages | grep sound`
from a Unraid terminal you will see which package got installed.

The packages in the release section are the pre compiled drivers which the plugin automatically determines to be compatible with your running Unraid version and downloads them as explained above.

Hope that makes sense.

**Comment by guniv** [comment]
That makes sense. Thank you!
